import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    backgroundColor: "#0D0D0D",
    height: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  tasks: {
    backgroundColor: "#191919",
    height: "100%",
    padding: 24,
  },
  inputGroup: {
    marginTop: -50,
    display: "flex",
    flexDirection: "row",
    gap: 4,
  },
  input: {
    flex: 1,
    height: 56,
    backgroundColor: "#262626",
    color: "#FFFF",
    fontSize: 16,
    marginRight: 12,
    borderWidth: 1,
    borderRadius: 6,
    padding: 16,
  },
  plusButton: {
    backgroundColor: "#1E6F9F",
    borderRadius: 6,
    padding: 18,
  },
  tasksInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 32,
    marginBottom: 20,
  },
  tasksCreated: {
    display: "flex",
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    height: 19,
  },
  tasksCreatedText: {
    color: "#4EA8DE",
    fontSize: 14,
    fontWeight: "bold",
  },
  tasksCreatedNumber: {
    backgroundColor: "#333333",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  tasksCreatedNumberText: {
    color: "#D9D9D9",
    fontWeight: "bold",
    fontSize: 12,
  },
  tasksFinished: {
    flexDirection: "row",
  },
  tasksFinishedText: {
    color: "#8284FA",
    fontSize: 14,
    fontWeight: "bold",
  },
  tasksList: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    justifyContent: "center",
    alignItems: "center",
    borderTopColor: "#333333",
    borderTopWidth: 1,
    paddingVertical: 48,
    paddingHorizontal: 20,
  },
  tasksListText: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  tasksListText1: {
    color: "#808080",
    fontWeight: "bold",
    fontSize: 14,
  },
  tasksListText2: {
    color: "#808080",
    fontSize: 14,
  },
  taskItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#262626",
    gap: 8,
    padding: 12,
    marginBottom: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#333333",
  },
  task: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    flex: 1,
  },
  taskTitle: {
    fontSize: 14,
    color: "#f2f2f2",
  },
  taskTitleSelected: {
    textDecorationLine: "line-through",
    color: "#808080",
  },
});
